[package]
edition = "2021"
name = "aoc-2022"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
color-eyre = "0.6"
itertools = "0.10"
rayon = "1.5"
